### ISSUE TITLE
Not hearing playback

### ISSUE THREAD

**Issue by cerupcat** [genedelisa/MIDIFileSequence#1]
Thanks for the great example!

However, I'm not hearing any playback. It loads a soundfont, loads a midi, and shows the reading playback in the console. However, it's not actually playing any audio.

Is this part not implemented? I noticed there isn't ever a call to playNoteOn.

**Comment by cerupcat** [comment]
Nevermind, I just realized that it was just taking a significant amount of time to load everything. 

It's playing now, but seems to only use piano (instead of multiple instruments).

**Comment by genedelisa** [comment]
You beat me to the answer! 

I wrote the example because the setup is quite involved and I wanted to show the simplest thing that could possibly work. The other reason is that I've seen very poor designs in other examples that mix UI code with sound code. Here the two concerns are separate.

I'm glad you found it useful. Have fun.

**Comment by cerupcat** [comment]
No problem, thanks again!
